name: Release

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout current version
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1

#      - name: Release
#        uses: fnkr/github-action-ghr@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
